package Networking.RpcProtocol;

public enum RequestType {
    GET_BEERS, GET_COCKTAILS, GET_COFFEES, GET_JUICES, GET_SOFT_DRINKS, GET_STRONG_DRINKS, GET_TEAS, GET_WINES,
    GET_CAKES, GET_ICE_SCREAM, GET_MEAT, GET_OTHER_DESSERTS, GET_PASTA, GET_PIZZA, GET_SALAD, GET_SEA_FOOD,
    GET_SMALL_BITES, GET_SOUP,

    ADD_ORDERED_DRINK, ADD_ORDERED_FOOD, GET_RATE_FOOD, RESET_RATE_FOOD, REMOVE_ORDERED_DRINK, REMOVE_ORDERED_FOOD,
    GET_ORDERED_DRINK, GET_ORDERED_FOOD,
    UPDATE_STARTER_FOOD, UPDATE_MAIN_FOOD, UPDATE_DESSERT_FOOD, ADD_STARER_FOOD, ADD_MAIN_FOOD, ADD_DESSERT_FOOD,
    REMOVE_STARTER_FOOD, REMOVE_MAIN_FOOD, REMOVE_DESSERT_FOOD,
    ADD_ALCOHOLIC_DRINK, REMOVE_ALCOHOLIC_DRINK, UPDATE_ALCOHOLIC_DRINK,
    ADD_NON_ALCOHOLIC_DRINK, REMOVE_NON_ALCOHOLIC_DRINK, UPDATE_NON_ALCOHOLIC_DRINK,
    INCREMENT_INDEX, SAVE_INDEX, GET_CURRENT_INDEX,
    ADD_ORDER_TO_ORDERS, ADD_ORDER_TO_ORDER_HISTORY, ADD_ORDER_TO_ORDER_DELIVERY, GET_ORDER_FROM_MAP,
    REMOVE_ORDER, ADD_ORDER_WITHOUT_MAP,
    ADD_USER, REMOVE_USER, UPDATE_USER, GET_USERS, FIND_USER, GET_USER_DATABASE,
    FIND_STARTER_FOOD, FIND_MAIN_FOOD, FIND_DESSERT_FOOD, FIND_ALCOHOLIC_DRINK, FIND_NON_ALCOHOLIC_DRINK,
    GET_DELIVERY_ORDERS, GET_ORDERS_HISTORY, GET_ORDERS, GET_ORDERS_MAP,
    GET_ORDER_DATABASE, GET_DELIVERY_ORDER_DATABASE, GET_ORDER_HISTORY_DATABASE,
    GET_OTHER_DATABASE, GET_PAYMENT_DATABASE, GET_PAYMENTS,
    GET_RESTORE_ORDER_ITEMS, ADD_PAYMENT, REMOVE_PAYMENT, ADD_TO_RESTORE_ORDER_ITEMS, REMOVE_FROM_RESTORE_ORDER_ITEMS,
    PUT_ORDER_IN_MAP,
    GET_ALL_DRINKS_TO_SEARCH, GET_ALL_FOOD_TO_SEARCH, GET_PAY_OBJECTS_MAP, GET_PAY_ORDERS_DATABASE,
    GET_OBJECT_FROM_MAP,
    GET_DELIVERY_ACCOUNTS, GET_DELIVERY_ACCOUNTS_DATABASE, ADD_ACCOUNT,
    GET_DRINK_DATABASE, GET_FOOD_DATABASE, GET_ORDERED_DELIVERY_DRINK, GET_ORDERED_DELIVERY_FOOD,
    ADD_ORDERED_DELIVERY_DRINK, ADD_ORDERED_DELIVERY_FOOD, REMOVE_ORDERED_DELIVERY_DRINK,
    REMOVE_ORDERED_DELIVERY_FOOD,
    ADD_THEME, GET_THEMES, DELETE_THEME,
    CLEAR_ORDER_ITEMS, CLEAR_DELIVERY_ORDER_ITEMS,
    GET_NEW_DRINKS, GET_NEW_FOOD, ADD_NEW_DRINKS, ADD_NEW_FOOD;
}
